run_02:
    tags:
        - docker
    image: debian:latest
    script:
        - apt-get update
        - apt-get install curl unzip lftp -y
        - curl -fsSL https://bun.sh/install | bash 
        - source /root/.bashrc
        - cd public
        - bun install 
        - cd ../
        - echo "...sync via lftp"
        - lftp -u $ftp_psi_user,$ftp_psi_pass -e 'set ssl:verify-certificate false; mirror --reverse --only-newer  --ignore-time --delete --exclude .git --exclude .htaccess --exclude logs  --verbose --parallel=10  --use-pget-n=10  public/ /psi/public/' asia.draconarius.com

        
        
        
